spring.application.name=Himcharm

# Server level configurations
server.servlet.context-path=/himcharm
server.port=9090

# DB level configurations...
spring.datasource.username=root
spring.datasource.password=Manoj@12
spring.datasource.url=jdbc:mysql://localhost:3306/himcharm

# JPA configurations.
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

# Automated birthday and anniversary campaigns
scheduler.time-zone=Asia/Kolkata
scheduler.automated-campaign.cron=0 32 8 * * *

# JWT Related Configurations
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=7200000

# Allowed Frontend Domain
security.domain.frontend-url=http://localhost:1173

# WhatsApp Cloud API configurations
whatsapp.api-base-url=${WHATSAPP_API_BASE_URL:https://graph.facebook.com/v23.0}
whatsapp.webhook.verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN:manoj-diksha-test-wao}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:1302459472948498}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN:EAAX49Vogl2gBSVhrQmtZBW2roxIoeZCQZBgKKSyQmV4pv0dJ3xyqcZCkm4Ron12ZBakPujZCXbbm8Dpm6tBdOJkMeZAfFgALwdKMt0Bslu831sHGIaSJcwMZC3fZCrfe5JA95ZBVqL9B8hlvLZC5zEnkMzEl4ZCbSZC4ZBkbNRSjkhZCMxB77ZCQL97w9PKo74H8oBBSAvl0cKRxAFcwjDZBHr1ojva2quNm8WZBj4KPStWWn9w1ii0J6ZAVsuk9Rv9a0nNmcbyUOwMXE9yQryPV9A98sZBsTI0EFnqs}

# WhatsApp Template configurations
whatsapp.template.invoice.name=bill_ready
whatsapp.template.anniversary.name=anniversary_special_offer
whatsapp.template.birthday.name=birthday_special_offer
whatsapp.template.anniversary.image-url=https://roopvibes.com/wp-content/uploads/2024/06/Happy-anniversary-greetings-card.jpg
whatsapp.template.birthday.image-url=https://i.ndtvimg.com/i/2017-10/diwali-istock_650x400_41508030401.jpg
whatsapp.template.festival.name=festival_special_offer
whatsapp.template.language=en

# http://localhost:5173/whatsapp/invoice?invoiceNumber=SU5WLVNULTMtMTAwNjI2LTE0
