spring.application.name=Himcharm

# Server level configurations
server.servlet.context-path=/himcharm
server.port=9090

# DB level configurations...
spring.datasource.username=root
spring.datasource.password=Manoj@12
spring.datasource.url=jdbc:mysql://localhost:3306/himcharm

# JPA configurations.
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

# JWT Related Configurations
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=7200000

# Allowed Frontend Domain
security.domain.frontend-url=http://localhost:1173

# Must match the Verify token entered in Meta App Dashboard.
whatsapp.webhook.verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN:manoj-diksha-test-wao}

