spring.application.name=Himcharm

# Server level configurations
server.servlet.context-path=/himcharm
server.port=9090

# DB level configurations...
spring.datasource.username=root
spring.datasource.password=Manoj@12
spring.datasource.url=jdbc:mysql://localhost:3306/himcharm

# JPA configurations.
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

# JWT Related Configurations
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=7200000

# Allowed Frontend Domain
security.domain.frontend-url=http://localhost:1173

# WhatsApp Cloud API configurations
whatsapp.api-base-url=${WHATSAPP_API_BASE_URL:https://graph.facebook.com/v23.0}
whatsapp.webhook.verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN:manoj-diksha-test-wao}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:1263811140157796}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN:EAAX49Vogl2gBSRAnaSdGnyyRXGHEUCIBG9IFJZBFDZCI1W5HZCn0tQYf8gjEzmFSjiphZASCZCXSbsM9CjN2hExJMPMyfqnJFPFk0BBAkBdqAxJKG8SZB3nIZAwRvsZCupa9t4dXFldochrNKPgbW4igzGMTvZCaIkCku4ou37PbqAZAjwooMZAvQF6ZCHY2AUtYFV6EsS9wMjHBIXtFATCxNuK7Mb7PZBnXSd74XCqHYOyBKgmmmHzzFIPyZAassSfrnIMcqRjLvg6u7qUCXdKuQZD}

# WhatsApp Template configurations
whatsapp.template.invoice.name=jaspers_market_order_confirmation_v1
whatsapp.template.invoice.language=en_US

